overrides:
  esbuild: ^0.28.1

patchedDependencies:
  '@uni-helper/uni-use': patches/@uni-helper__uni-use.patch
  pinia: patches/pinia.patch

allowBuilds:
  '@parcel/watcher': true
  '@uni-helper/unocss-preset-uni': true
  core-js: true
  core-js-pure: true
  esbuild: true
  unrs-resolver: true
  vue-demi: true

ignoreWorkspaceRootCheck: true
minimumReleaseAge: 0
packageManagerStrict: false
shamefullyHoist: true
