overrides:
  esbuild: ^0.25.12
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@uni-helper/unocss-preset-uni'
  - core-js
  - esbuild
  - unrs-resolver
  - vue-demi

patchedDependencies:
  '@uni-helper/uni-use': patches/@uni-helper__uni-use.patch
  pinia: patches/pinia.patch
