overrides:
  esbuild: ^0.25.10
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@uni-helper/unocss-preset-uni'
  - core-js
  - esbuild
  - unrs-resolver
  - vue-demi
patchedDependencies:
  pinia: patches/pinia.patch
