overrides:
  esbuild: ^0.28.2

patchedDependencies:
  '@dcloudio/uni-mp-vite@3.0.0-alpha-5030120260930001': patches/@dcloudio__uni-mp-vite@3.0.0-alpha-5030120260930001.patch
  '@uni-helper/uni-use': patches/@uni-helper__uni-use.patch
  wot-design-uni@1.14.0: patches/wot-design-uni@1.14.0.patch

allowBuilds:
  '@parcel/watcher': true
  '@uni-helper/unocss-preset-uni': true
  core-js: true
  core-js-pure: true
  esbuild: true
  unrs-resolver: true
  vue-demi: true

ignoreWorkspaceRootCheck: true
minimumReleaseAge: 0
pmOnFail: warn
shamefullyHoist: true
