/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UniEcharts: typeof import('uni-echarts')['UniEcharts']
    WdButton: typeof import('wot-design-uni/components/wd-button/wd-button.vue')['WdButton']
    WdSwiper: typeof import('wot-design-uni/components/wd-swiper/wd-swiper.vue')['WdSwiper']
  }
}

// For TSX support
declare global {
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const UniEcharts: typeof import('uni-echarts')['UniEcharts']
  const WdButton: typeof import('wot-design-uni/components/wd-button/wd-button.vue')['WdButton']
  const WdSwiper: typeof import('wot-design-uni/components/wd-swiper/wd-swiper.vue')['WdSwiper']
}